version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
        interval: 1s
        retries: 100
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      mysql:
        condition: service_healthy
    build: ./
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    stdin_open: true
    tty: true
volumes: 
  db:

